# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

#                         srun.swg                            #
#
# This is the basic code that is needed at run time within R to
# provide and define the relevant classes.  It is included
# automatically in the generated code by copying the contents of
# srun.swg into the newly created binding code.


# This could be provided as a separate run-time library but this
# approach allows the code to be included directly into the
# generated bindings and so removes the need to have and install an
# additional library.  We may however end up with multiple copies of
# this and some confusion at run-time as to which class to use. This
# is an issue when we use NAMESPACES as we may need to export certain
# classes.

######################################################################

if(length(getClassDef("RSWIGStruct")) == 0) 
  setClass("RSWIGStruct", representation("VIRTUAL"))



if(length(getClassDef("ExternalReference")) == 0) 
# Should be virtual but this means it loses its slots currently
#representation("VIRTUAL")
  setClass("ExternalReference", representation( ref = "externalptr"))



if(length(getClassDef("NativeRoutinePointer")) == 0) 
  setClass("NativeRoutinePointer", 
              representation(parameterTypes = "character",
                             returnType = "character",
                             "VIRTUAL"), 
              contains = "ExternalReference")

if(length(getClassDef("CRoutinePointer")) == 0) 
  setClass("CRoutinePointer", contains = "NativeRoutinePointer")


if(length(getClassDef("EnumerationValue")) == 0) 
  setClass("EnumerationValue", contains = "integer")


if(!isGeneric("copyToR")) 
 setGeneric("copyToR",
            function(value, obj = new(gsub("Ref$", "", class(value)))) 
               standardGeneric("copyToR"
           ))

setGeneric("delete", function(obj) standardGeneric("delete"))


SWIG_createNewRef = 
function(className, ..., append = TRUE)
{
  f = get(paste("new", className, sep = "_"), mode = "function")

  f(...)
}

if(!isGeneric("copyToC")) 
 setGeneric("copyToC", 
             function(value, obj = SWIG_createNewRef(class(value)))
              standardGeneric("copyToC"
            ))


# 
defineEnumeration =
function(name, .values, where = topenv(parent.frame()), suffix = "Value")
{
   # Mirror the class definitions via the E analogous to .__C__
  defName = paste(".__E__", name, sep = "")
  delayedAssign(defName,  .values, assign.env = where)

  if(nchar(suffix))
    name = paste(name, suffix, sep = "")

  setClass(name, contains = "EnumerationValue", where = where)
}

enumToInteger <- function(name,type)
{
   if (is.character(name)) {
   ans <- as.integer(get(paste(".__E__", type, sep = ""))[name])
   if (is.na(ans)) {warning("enum not found ", name, " ", type)}
   ans
   } 
}

enumFromInteger =
function(i,type)
{
  itemlist <- get(paste(".__E__", type, sep=""))
  names(itemlist)[match(i, itemlist)]
}

coerceIfNotSubclass =
function(obj, type) 
{
    if(!is(obj, type)) {as(obj, type)} else obj
}


setClass("SWIGArray", representation(dims = "integer"), contains = "ExternalReference")

setMethod("length", "SWIGArray", function(x) x@dims[1])


defineEnumeration("SCopyReferences",
                   .values = c( "FALSE" = 0, "TRUE" = 1, "DEEP" = 2))

assert = 
function(condition, message = "")
{
  if(!condition)
    stop(message)

  TRUE
}


if(FALSE) {
print.SWIGFunction =
function(x, ...)
 {
 }
}


#######################################################################

R_SWIG_getCallbackFunctionStack =
function()
{
    # No PACKAGE argument as we don't know what the DLL is.
  .Call("R_SWIG_debug_getCallbackFunctionData")
}

R_SWIG_addCallbackFunctionStack =
function(fun, userData = NULL)
{
    # No PACKAGE argument as we don't know what the DLL is.
  .Call("R_SWIG_R_pushCallbackFunctionData", fun, userData)
}


#######################################################################






setMethod('[', "ExternalReference",
function(x,i,j, ..., drop=TRUE) 
if (!is.null(x$"__getitem__")) 
sapply(i, function(n) x$"__getitem__"(i=as.integer(n-1))))

setMethod('[<-' , "ExternalReference",
function(x,i,j, ..., value) 
if (!is.null(x$"__setitem__")) {
sapply(1:length(i), function(n) 
x$"__setitem__"(i=as.integer(i[n]-1), x=value[n]))
x
})

setAs('ExternalReference', 'character',
function(from) {if (!is.null(from$"__str__")) from$"__str__"()})

suppressMessages(suppressWarnings(setMethod('print', 'ExternalReference',
function(x) {print(as(x, "character"))})))

# Start of iapws92_sat_p_T

`iapws92_sat_p_T` = function(T, .copy = FALSE)
{
  ;.Call('R_swig_iapws92_sat_p_T', T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws92_sat_p_T`, 'returnType') = 'numeric'
attr(`iapws92_sat_p_T`, "inputTypes") = c('numeric')
class(`iapws92_sat_p_T`) = c("SWIGFunction", class('iapws92_sat_p_T'))

# Start of iapws92_sat_T_p

`iapws92_sat_T_p` = function(p, .copy = FALSE)
{
  ;.Call('R_swig_iapws92_sat_T_p', p, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws92_sat_T_p`, 'returnType') = 'numeric'
attr(`iapws92_sat_T_p`, "inputTypes") = c('numeric')
class(`iapws92_sat_T_p`) = c("SWIGFunction", class('iapws92_sat_T_p'))

# Start of iapws92_sat_dp_dT_T

`iapws92_sat_dp_dT_T` = function(T, .copy = FALSE)
{
  ;.Call('R_swig_iapws92_sat_dp_dT_T', T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws92_sat_dp_dT_T`, 'returnType') = 'numeric'
attr(`iapws92_sat_dp_dT_T`, "inputTypes") = c('numeric')
class(`iapws92_sat_dp_dT_T`) = c("SWIGFunction", class('iapws92_sat_dp_dT_T'))

# Start of iapws92_sat_rhol_T

`iapws92_sat_rhol_T` = function(T, .copy = FALSE)
{
  ;.Call('R_swig_iapws92_sat_rhol_T', T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws92_sat_rhol_T`, 'returnType') = 'numeric'
attr(`iapws92_sat_rhol_T`, "inputTypes") = c('numeric')
class(`iapws92_sat_rhol_T`) = c("SWIGFunction", class('iapws92_sat_rhol_T'))

# Start of iapws92_sat_drhol_dT_T

`iapws92_sat_drhol_dT_T` = function(T, .copy = FALSE)
{
  ;.Call('R_swig_iapws92_sat_drhol_dT_T', T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws92_sat_drhol_dT_T`, 'returnType') = 'numeric'
attr(`iapws92_sat_drhol_dT_T`, "inputTypes") = c('numeric')
class(`iapws92_sat_drhol_dT_T`) = c("SWIGFunction", class('iapws92_sat_drhol_dT_T'))

# Start of iapws92_sat_rhov_T

`iapws92_sat_rhov_T` = function(T, .copy = FALSE)
{
  ;.Call('R_swig_iapws92_sat_rhov_T', T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws92_sat_rhov_T`, 'returnType') = 'numeric'
attr(`iapws92_sat_rhov_T`, "inputTypes") = c('numeric')
class(`iapws92_sat_rhov_T`) = c("SWIGFunction", class('iapws92_sat_rhov_T'))

# Start of iapws92_sat_alpha

`iapws92_sat_alpha` = function(T, .copy = FALSE)
{
  ;.Call('R_swig_iapws92_sat_alpha', T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws92_sat_alpha`, 'returnType') = 'numeric'
attr(`iapws92_sat_alpha`, "inputTypes") = c('numeric')
class(`iapws92_sat_alpha`) = c("SWIGFunction", class('iapws92_sat_alpha'))

# Start of iapws92_sat_phi

`iapws92_sat_phi` = function(T, .copy = FALSE)
{
  ;.Call('R_swig_iapws92_sat_phi', T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws92_sat_phi`, 'returnType') = 'numeric'
attr(`iapws92_sat_phi`, "inputTypes") = c('numeric')
class(`iapws92_sat_phi`) = c("SWIGFunction", class('iapws92_sat_phi'))

# Start of iapws92_sat_hl_T

`iapws92_sat_hl_T` = function(T, .copy = FALSE)
{
  ;.Call('R_swig_iapws92_sat_hl_T', T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws92_sat_hl_T`, 'returnType') = 'numeric'
attr(`iapws92_sat_hl_T`, "inputTypes") = c('numeric')
class(`iapws92_sat_hl_T`) = c("SWIGFunction", class('iapws92_sat_hl_T'))

# Start of iapws92_sat_hv_T

`iapws92_sat_hv_T` = function(T, .copy = FALSE)
{
  ;.Call('R_swig_iapws92_sat_hv_T', T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws92_sat_hv_T`, 'returnType') = 'numeric'
attr(`iapws92_sat_hv_T`, "inputTypes") = c('numeric')
class(`iapws92_sat_hv_T`) = c("SWIGFunction", class('iapws92_sat_hv_T'))

# Start of iapws92_sat_sl_T

`iapws92_sat_sl_T` = function(T, .copy = FALSE)
{
  ;.Call('R_swig_iapws92_sat_sl_T', T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws92_sat_sl_T`, 'returnType') = 'numeric'
attr(`iapws92_sat_sl_T`, "inputTypes") = c('numeric')
class(`iapws92_sat_sl_T`) = c("SWIGFunction", class('iapws92_sat_sl_T'))

# Start of iapws92_sat_sg_T

`iapws92_sat_sg_T` = function(T, .copy = FALSE)
{
  ;.Call('R_swig_iapws92_sat_sg_T', T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws92_sat_sg_T`, 'returnType') = 'numeric'
attr(`iapws92_sat_sg_T`, "inputTypes") = c('numeric')
class(`iapws92_sat_sg_T`) = c("SWIGFunction", class('iapws92_sat_sg_T'))

# Start of iapws95_get_rhoc

`iapws95_get_rhoc` = function(.copy = FALSE)
{
  ;.Call('R_swig_iapws95_get_rhoc', as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_get_rhoc`, 'returnType') = 'numeric'
class(`iapws95_get_rhoc`) = c("SWIGFunction", class('iapws95_get_rhoc'))

# Start of iapws95_get_Tc

`iapws95_get_Tc` = function(.copy = FALSE)
{
  ;.Call('R_swig_iapws95_get_Tc', as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_get_Tc`, 'returnType') = 'numeric'
class(`iapws95_get_Tc`) = c("SWIGFunction", class('iapws95_get_Tc'))

# Start of iapws95_get_pc

`iapws95_get_pc` = function(.copy = FALSE)
{
  ;.Call('R_swig_iapws95_get_pc', as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_get_pc`, 'returnType') = 'numeric'
class(`iapws95_get_pc`) = c("SWIGFunction", class('iapws95_get_pc'))

# Start of iapws95_get_hc

`iapws95_get_hc` = function(.copy = FALSE)
{
  ;.Call('R_swig_iapws95_get_hc', as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_get_hc`, 'returnType') = 'numeric'
class(`iapws95_get_hc`) = c("SWIGFunction", class('iapws95_get_hc'))

# Start of iapws95_get_Tt

`iapws95_get_Tt` = function(.copy = FALSE)
{
  ;.Call('R_swig_iapws95_get_Tt', as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_get_Tt`, 'returnType') = 'numeric'
class(`iapws95_get_Tt`) = c("SWIGFunction", class('iapws95_get_Tt'))

# Start of iapws95_get_pt_approx

`iapws95_get_pt_approx` = function(.copy = FALSE)
{
  ;.Call('R_swig_iapws95_get_pt_approx', as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_get_pt_approx`, 'returnType') = 'numeric'
class(`iapws95_get_pt_approx`) = c("SWIGFunction", class('iapws95_get_pt_approx'))

# Start of iapws95_get_rholt

`iapws95_get_rholt` = function(.copy = FALSE)
{
  ;.Call('R_swig_iapws95_get_rholt', as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_get_rholt`, 'returnType') = 'numeric'
class(`iapws95_get_rholt`) = c("SWIGFunction", class('iapws95_get_rholt'))

# Start of iapws95_get_rhovt

`iapws95_get_rhovt` = function(.copy = FALSE)
{
  ;.Call('R_swig_iapws95_get_rhovt', as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_get_rhovt`, 'returnType') = 'numeric'
class(`iapws95_get_rhovt`) = c("SWIGFunction", class('iapws95_get_rhovt'))

# Start of iapws95_get_hlt

`iapws95_get_hlt` = function(.copy = FALSE)
{
  ;.Call('R_swig_iapws95_get_hlt', as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_get_hlt`, 'returnType') = 'numeric'
class(`iapws95_get_hlt`) = c("SWIGFunction", class('iapws95_get_hlt'))

# Start of iapws95_get_hvt

`iapws95_get_hvt` = function(.copy = FALSE)
{
  ;.Call('R_swig_iapws95_get_hvt', as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_get_hvt`, 'returnType') = 'numeric'
class(`iapws95_get_hvt`) = c("SWIGFunction", class('iapws95_get_hvt'))

# Start of iapws95_f_rhoT

`iapws95_f_rhoT` = function(rho, T, .copy = FALSE)
{
  ;.Call('R_swig_iapws95_f_rhoT', rho, T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_f_rhoT`, 'returnType') = 'numeric'
attr(`iapws95_f_rhoT`, "inputTypes") = c('numeric', 'numeric')
class(`iapws95_f_rhoT`) = c("SWIGFunction", class('iapws95_f_rhoT'))

# Start of iapws95_g_rhoT

`iapws95_g_rhoT` = function(rho, T, .copy = FALSE)
{
  ;.Call('R_swig_iapws95_g_rhoT', rho, T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_g_rhoT`, 'returnType') = 'numeric'
attr(`iapws95_g_rhoT`, "inputTypes") = c('numeric', 'numeric')
class(`iapws95_g_rhoT`) = c("SWIGFunction", class('iapws95_g_rhoT'))

# Start of iapws95_u_rhoT

`iapws95_u_rhoT` = function(rho, T, .copy = FALSE)
{
  ;.Call('R_swig_iapws95_u_rhoT', rho, T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_u_rhoT`, 'returnType') = 'numeric'
attr(`iapws95_u_rhoT`, "inputTypes") = c('numeric', 'numeric')
class(`iapws95_u_rhoT`) = c("SWIGFunction", class('iapws95_u_rhoT'))

# Start of iapws95_h_rhoT

`iapws95_h_rhoT` = function(rho, T, .copy = FALSE)
{
  ;.Call('R_swig_iapws95_h_rhoT', rho, T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_h_rhoT`, 'returnType') = 'numeric'
attr(`iapws95_h_rhoT`, "inputTypes") = c('numeric', 'numeric')
class(`iapws95_h_rhoT`) = c("SWIGFunction", class('iapws95_h_rhoT'))

# Start of iapws95_h_pT

`iapws95_h_pT` = function(p, T, .copy = FALSE)
{
  ;.Call('R_swig_iapws95_h_pT', p, T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_h_pT`, 'returnType') = 'numeric'
attr(`iapws95_h_pT`, "inputTypes") = c('numeric', 'numeric')
class(`iapws95_h_pT`) = c("SWIGFunction", class('iapws95_h_pT'))

# Start of iapws95_s_rhoT

`iapws95_s_rhoT` = function(rho, T, .copy = FALSE)
{
  ;.Call('R_swig_iapws95_s_rhoT', rho, T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_s_rhoT`, 'returnType') = 'numeric'
attr(`iapws95_s_rhoT`, "inputTypes") = c('numeric', 'numeric')
class(`iapws95_s_rhoT`) = c("SWIGFunction", class('iapws95_s_rhoT'))

# Start of iapws95_p_rhoT

`iapws95_p_rhoT` = function(rho, T, .copy = FALSE)
{
  ;.Call('R_swig_iapws95_p_rhoT', rho, T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_p_rhoT`, 'returnType') = 'numeric'
attr(`iapws95_p_rhoT`, "inputTypes") = c('numeric', 'numeric')
class(`iapws95_p_rhoT`) = c("SWIGFunction", class('iapws95_p_rhoT'))

# Start of iapws95_cp_rhoT

`iapws95_cp_rhoT` = function(rho, T, .copy = FALSE)
{
  ;.Call('R_swig_iapws95_cp_rhoT', rho, T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_cp_rhoT`, 'returnType') = 'numeric'
attr(`iapws95_cp_rhoT`, "inputTypes") = c('numeric', 'numeric')
class(`iapws95_cp_rhoT`) = c("SWIGFunction", class('iapws95_cp_rhoT'))

# Start of iapws95_cv_rhoT

`iapws95_cv_rhoT` = function(rho, T, .copy = FALSE)
{
  ;.Call('R_swig_iapws95_cv_rhoT', rho, T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_cv_rhoT`, 'returnType') = 'numeric'
attr(`iapws95_cv_rhoT`, "inputTypes") = c('numeric', 'numeric')
class(`iapws95_cv_rhoT`) = c("SWIGFunction", class('iapws95_cv_rhoT'))

# Start of iapws95_rho_pT

`iapws95_rho_pT` = function(p, T, .copy = FALSE)
{
  ;.Call('R_swig_iapws95_rho_pT', p, T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_rho_pT`, 'returnType') = 'numeric'
attr(`iapws95_rho_pT`, "inputTypes") = c('numeric', 'numeric')
class(`iapws95_rho_pT`) = c("SWIGFunction", class('iapws95_rho_pT'))

# Start of iapws95_rho_ph

`iapws95_rho_ph` = function(p, h, .copy = FALSE)
{
  ;.Call('R_swig_iapws95_rho_ph', p, h, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_rho_ph`, 'returnType') = 'numeric'
attr(`iapws95_rho_ph`, "inputTypes") = c('numeric', 'numeric')
class(`iapws95_rho_ph`) = c("SWIGFunction", class('iapws95_rho_ph'))

# Start of iapws95_T_rhop

`iapws95_T_rhop` = function(rho, p, .copy = FALSE)
{
  ;.Call('R_swig_iapws95_T_rhop', rho, p, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_T_rhop`, 'returnType') = 'numeric'
attr(`iapws95_T_rhop`, "inputTypes") = c('numeric', 'numeric')
class(`iapws95_T_rhop`) = c("SWIGFunction", class('iapws95_T_rhop'))

# Start of iapws95_T_ph

`iapws95_T_ph` = function(p, h, .copy = FALSE)
{
  ;.Call('R_swig_iapws95_T_ph', p, h, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_T_ph`, 'returnType') = 'numeric'
attr(`iapws95_T_ph`, "inputTypes") = c('numeric', 'numeric')
class(`iapws95_T_ph`) = c("SWIGFunction", class('iapws95_T_ph'))

# Start of iapws95_wv_ph

`iapws95_wv_ph` = function(p, h, .copy = FALSE)
{
  ;.Call('R_swig_iapws95_wv_ph', p, h, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_wv_ph`, 'returnType') = 'numeric'
attr(`iapws95_wv_ph`, "inputTypes") = c('numeric', 'numeric')
class(`iapws95_wv_ph`) = c("SWIGFunction", class('iapws95_wv_ph'))

# Start of iapws95_sat_p_T

`iapws95_sat_p_T` = function(T, .copy = FALSE)
{
  ;.Call('R_swig_iapws95_sat_p_T', T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_sat_p_T`, 'returnType') = 'numeric'
attr(`iapws95_sat_p_T`, "inputTypes") = c('numeric')
class(`iapws95_sat_p_T`) = c("SWIGFunction", class('iapws95_sat_p_T'))

# Start of iapws95_sat_T_p

`iapws95_sat_T_p` = function(p, .copy = FALSE)
{
  ;.Call('R_swig_iapws95_sat_T_p', p, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_sat_T_p`, 'returnType') = 'numeric'
attr(`iapws95_sat_T_p`, "inputTypes") = c('numeric')
class(`iapws95_sat_T_p`) = c("SWIGFunction", class('iapws95_sat_T_p'))

# Start of iapws95_sat_rhol_T

`iapws95_sat_rhol_T` = function(T, .copy = FALSE)
{
  ;.Call('R_swig_iapws95_sat_rhol_T', T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_sat_rhol_T`, 'returnType') = 'numeric'
attr(`iapws95_sat_rhol_T`, "inputTypes") = c('numeric')
class(`iapws95_sat_rhol_T`) = c("SWIGFunction", class('iapws95_sat_rhol_T'))

# Start of iapws95_sat_rhol_p

`iapws95_sat_rhol_p` = function(p, .copy = FALSE)
{
  ;.Call('R_swig_iapws95_sat_rhol_p', p, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_sat_rhol_p`, 'returnType') = 'numeric'
attr(`iapws95_sat_rhol_p`, "inputTypes") = c('numeric')
class(`iapws95_sat_rhol_p`) = c("SWIGFunction", class('iapws95_sat_rhol_p'))

# Start of iapws95_sat_rhov_T

`iapws95_sat_rhov_T` = function(T, .copy = FALSE)
{
  ;.Call('R_swig_iapws95_sat_rhov_T', T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_sat_rhov_T`, 'returnType') = 'numeric'
attr(`iapws95_sat_rhov_T`, "inputTypes") = c('numeric')
class(`iapws95_sat_rhov_T`) = c("SWIGFunction", class('iapws95_sat_rhov_T'))

# Start of iapws95_sat_rhov_p

`iapws95_sat_rhov_p` = function(p, .copy = FALSE)
{
  ;.Call('R_swig_iapws95_sat_rhov_p', p, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_sat_rhov_p`, 'returnType') = 'numeric'
attr(`iapws95_sat_rhov_p`, "inputTypes") = c('numeric')
class(`iapws95_sat_rhov_p`) = c("SWIGFunction", class('iapws95_sat_rhov_p'))

# Start of iapws95_sat_hl_p

`iapws95_sat_hl_p` = function(p, .copy = FALSE)
{
  ;.Call('R_swig_iapws95_sat_hl_p', p, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_sat_hl_p`, 'returnType') = 'numeric'
attr(`iapws95_sat_hl_p`, "inputTypes") = c('numeric')
class(`iapws95_sat_hl_p`) = c("SWIGFunction", class('iapws95_sat_hl_p'))

# Start of iapws95_sat_hl_T

`iapws95_sat_hl_T` = function(T, .copy = FALSE)
{
  ;.Call('R_swig_iapws95_sat_hl_T', T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_sat_hl_T`, 'returnType') = 'numeric'
attr(`iapws95_sat_hl_T`, "inputTypes") = c('numeric')
class(`iapws95_sat_hl_T`) = c("SWIGFunction", class('iapws95_sat_hl_T'))

# Start of iapws95_sat_hv_p

`iapws95_sat_hv_p` = function(p, .copy = FALSE)
{
  ;.Call('R_swig_iapws95_sat_hv_p', p, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_sat_hv_p`, 'returnType') = 'numeric'
attr(`iapws95_sat_hv_p`, "inputTypes") = c('numeric')
class(`iapws95_sat_hv_p`) = c("SWIGFunction", class('iapws95_sat_hv_p'))

# Start of iapws95_sat_hv_T

`iapws95_sat_hv_T` = function(T, .copy = FALSE)
{
  ;.Call('R_swig_iapws95_sat_hv_T', T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws95_sat_hv_T`, 'returnType') = 'numeric'
attr(`iapws95_sat_hv_T`, "inputTypes") = c('numeric')
class(`iapws95_sat_hv_T`) = c("SWIGFunction", class('iapws95_sat_hv_T'))

# Start of iapws85_viscosity_rhoT

`iapws85_viscosity_rhoT` = function(rho, T, .copy = FALSE)
{
  ;.Call('R_swig_iapws85_viscosity_rhoT', rho, T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws85_viscosity_rhoT`, 'returnType') = 'numeric'
attr(`iapws85_viscosity_rhoT`, "inputTypes") = c('numeric', 'numeric')
class(`iapws85_viscosity_rhoT`) = c("SWIGFunction", class('iapws85_viscosity_rhoT'))

# Start of iapws08_viscosity_rhoT

`iapws08_viscosity_rhoT` = function(rho, T, .copy = FALSE)
{
  ;.Call('R_swig_iapws08_viscosity_rhoT', rho, T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws08_viscosity_rhoT`, 'returnType') = 'numeric'
attr(`iapws08_viscosity_rhoT`, "inputTypes") = c('numeric', 'numeric')
class(`iapws08_viscosity_rhoT`) = c("SWIGFunction", class('iapws08_viscosity_rhoT'))

# Start of iapws08_viscosity_rhoT_simplified

`iapws08_viscosity_rhoT_simplified` = function(rho, T, .copy = FALSE)
{
  ;.Call('R_swig_iapws08_viscosity_rhoT_simplified', rho, T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws08_viscosity_rhoT_simplified`, 'returnType') = 'numeric'
attr(`iapws08_viscosity_rhoT_simplified`, "inputTypes") = c('numeric', 'numeric')
class(`iapws08_viscosity_rhoT_simplified`) = c("SWIGFunction", class('iapws08_viscosity_rhoT_simplified'))

# Start of iapws11_thermal_conductivity_rhoT

`iapws11_thermal_conductivity_rhoT` = function(rho, T, .copy = FALSE)
{
  ;.Call('R_swig_iapws11_thermal_conductivity_rhoT', rho, T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`iapws11_thermal_conductivity_rhoT`, 'returnType') = 'numeric'
attr(`iapws11_thermal_conductivity_rhoT`, "inputTypes") = c('numeric', 'numeric')
class(`iapws11_thermal_conductivity_rhoT`) = c("SWIGFunction", class('iapws11_thermal_conductivity_rhoT'))

# Start of driesner07_NaCl_VLH_p

`driesner07_NaCl_VLH_p` = function(.copy = FALSE)
{
  ;.Call('R_swig_driesner07_NaCl_VLH_p', as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_NaCl_VLH_p`, 'returnType') = 'numeric'
class(`driesner07_NaCl_VLH_p`) = c("SWIGFunction", class('driesner07_NaCl_VLH_p'))

# Start of driesner07_NaCl_VLH_T

`driesner07_NaCl_VLH_T` = function(.copy = FALSE)
{
  ;.Call('R_swig_driesner07_NaCl_VLH_T', as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_NaCl_VLH_T`, 'returnType') = 'numeric'
class(`driesner07_NaCl_VLH_T`) = c("SWIGFunction", class('driesner07_NaCl_VLH_T'))

# Start of driesner07_NaCl_VLH_TC

`driesner07_NaCl_VLH_TC` = function(.copy = FALSE)
{
  ;.Call('R_swig_driesner07_NaCl_VLH_TC', as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_NaCl_VLH_TC`, 'returnType') = 'numeric'
class(`driesner07_NaCl_VLH_TC`) = c("SWIGFunction", class('driesner07_NaCl_VLH_TC'))

# Start of driesner07_NaCl_VLH_h_halite

`driesner07_NaCl_VLH_h_halite` = function(.copy = FALSE)
{
  ;.Call('R_swig_driesner07_NaCl_VLH_h_halite', as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_NaCl_VLH_h_halite`, 'returnType') = 'numeric'
class(`driesner07_NaCl_VLH_h_halite`) = c("SWIGFunction", class('driesner07_NaCl_VLH_h_halite'))

# Start of driesner07_NaCl_LH_T_p

`driesner07_NaCl_LH_T_p` = function(p, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_NaCl_LH_T_p', p, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_NaCl_LH_T_p`, 'returnType') = 'numeric'
attr(`driesner07_NaCl_LH_T_p`, "inputTypes") = c('numeric')
class(`driesner07_NaCl_LH_T_p`) = c("SWIGFunction", class('driesner07_NaCl_LH_T_p'))

# Start of driesner07_NaCl_VH_p_T

`driesner07_NaCl_VH_p_T` = function(T, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_NaCl_VH_p_T', T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_NaCl_VH_p_T`, 'returnType') = 'numeric'
attr(`driesner07_NaCl_VH_p_T`, "inputTypes") = c('numeric')
class(`driesner07_NaCl_VH_p_T`) = c("SWIGFunction", class('driesner07_NaCl_VH_p_T'))

# Start of driesner07_NaCl_VL_p_T

`driesner07_NaCl_VL_p_T` = function(T, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_NaCl_VL_p_T', T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_NaCl_VL_p_T`, 'returnType') = 'numeric'
attr(`driesner07_NaCl_VL_p_T`, "inputTypes") = c('numeric')
class(`driesner07_NaCl_VL_p_T`) = c("SWIGFunction", class('driesner07_NaCl_VL_p_T'))

# Start of driesner07_NaCl_sat_p_T

`driesner07_NaCl_sat_p_T` = function(T, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_NaCl_sat_p_T', T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_NaCl_sat_p_T`, 'returnType') = 'numeric'
attr(`driesner07_NaCl_sat_p_T`, "inputTypes") = c('numeric')
class(`driesner07_NaCl_sat_p_T`) = c("SWIGFunction", class('driesner07_NaCl_sat_p_T'))

# Start of driesner07_NaCl_H_rho_pT

`driesner07_NaCl_H_rho_pT` = function(p_Pa, T_K, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_NaCl_H_rho_pT', p_Pa, T_K, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_NaCl_H_rho_pT`, 'returnType') = 'numeric'
attr(`driesner07_NaCl_H_rho_pT`, "inputTypes") = c('numeric', 'numeric')
class(`driesner07_NaCl_H_rho_pT`) = c("SWIGFunction", class('driesner07_NaCl_H_rho_pT'))

# Start of driesner07_NaCl_H_h_pT

`driesner07_NaCl_H_h_pT` = function(p_Pa, T_K, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_NaCl_H_h_pT', p_Pa, T_K, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_NaCl_H_h_pT`, 'returnType') = 'numeric'
attr(`driesner07_NaCl_H_h_pT`, "inputTypes") = c('numeric', 'numeric')
class(`driesner07_NaCl_H_h_pT`) = c("SWIGFunction", class('driesner07_NaCl_H_h_pT'))

# Start of driesner07_NaCl_H_cp_pT

`driesner07_NaCl_H_cp_pT` = function(p_Pa, T_K, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_NaCl_H_cp_pT', p_Pa, T_K, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_NaCl_H_cp_pT`, 'returnType') = 'numeric'
attr(`driesner07_NaCl_H_cp_pT`, "inputTypes") = c('numeric', 'numeric')
class(`driesner07_NaCl_H_cp_pT`) = c("SWIGFunction", class('driesner07_NaCl_H_cp_pT'))

# Start of driesner07_NaCl_L_rho_pT

`driesner07_NaCl_L_rho_pT` = function(p_Pa, T_K, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_NaCl_L_rho_pT', p_Pa, T_K, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_NaCl_L_rho_pT`, 'returnType') = 'numeric'
attr(`driesner07_NaCl_L_rho_pT`, "inputTypes") = c('numeric', 'numeric')
class(`driesner07_NaCl_L_rho_pT`) = c("SWIGFunction", class('driesner07_NaCl_L_rho_pT'))

# Start of driesner07_NaCl_L_compressibility_pT

`driesner07_NaCl_L_compressibility_pT` = function(T_K, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_NaCl_L_compressibility_pT', T_K, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_NaCl_L_compressibility_pT`, 'returnType') = 'numeric'
attr(`driesner07_NaCl_L_compressibility_pT`, "inputTypes") = c('numeric')
class(`driesner07_NaCl_L_compressibility_pT`) = c("SWIGFunction", class('driesner07_NaCl_L_compressibility_pT'))

# Start of driesner07_H2O_NaCl_phase_type

`driesner07_H2O_NaCl_phase_type` = function(p_Pa, T_K, x, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_phase_type', p_Pa, T_K, x, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_phase_type`, 'returnType') = 'integer'
attr(`driesner07_H2O_NaCl_phase_type`, "inputTypes") = c('numeric', 'numeric', 'numeric')
class(`driesner07_H2O_NaCl_phase_type`) = c("SWIGFunction", class('driesner07_H2O_NaCl_phase_type'))

# Start of driesner07_H2O_NaCl_pc_T

`driesner07_H2O_NaCl_pc_T` = function(T, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_pc_T', T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_pc_T`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_pc_T`, "inputTypes") = c('numeric')
class(`driesner07_H2O_NaCl_pc_T`) = c("SWIGFunction", class('driesner07_H2O_NaCl_pc_T'))

# Start of driesner07_H2O_NaCl_pc_T2

`driesner07_H2O_NaCl_pc_T2` = function(T, use_satp, .copy = FALSE)
{
  use_satp = as.logical(use_satp);
  ;.Call('R_swig_driesner07_H2O_NaCl_pc_T2', T, use_satp, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_pc_T2`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_pc_T2`, "inputTypes") = c('numeric', 'logical')
class(`driesner07_H2O_NaCl_pc_T2`) = c("SWIGFunction", class('driesner07_H2O_NaCl_pc_T2'))

# Start of driesner07_H2O_NaCl_xc_T

`driesner07_H2O_NaCl_xc_T` = function(T, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_xc_T', T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_xc_T`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_xc_T`, "inputTypes") = c('numeric')
class(`driesner07_H2O_NaCl_xc_T`) = c("SWIGFunction", class('driesner07_H2O_NaCl_xc_T'))

# Start of driesner07_H2O_NaCl_Tc_x

`driesner07_H2O_NaCl_Tc_x` = function(x, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_Tc_x', x, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_Tc_x`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_Tc_x`, "inputTypes") = c('numeric')
class(`driesner07_H2O_NaCl_Tc_x`) = c("SWIGFunction", class('driesner07_H2O_NaCl_Tc_x'))

# Start of driesner07_H2O_NaCl_VL_xl_pT

`driesner07_H2O_NaCl_VL_xl_pT` = function(p, T, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_VL_xl_pT', p, T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_VL_xl_pT`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_VL_xl_pT`, "inputTypes") = c('numeric', 'numeric')
class(`driesner07_H2O_NaCl_VL_xl_pT`) = c("SWIGFunction", class('driesner07_H2O_NaCl_VL_xl_pT'))

# Start of driesner07_H2O_NaCl_VL_xv_pT

`driesner07_H2O_NaCl_VL_xv_pT` = function(p, T, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_VL_xv_pT', p, T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_VL_xv_pT`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_VL_xv_pT`, "inputTypes") = c('numeric', 'numeric')
class(`driesner07_H2O_NaCl_VL_xv_pT`) = c("SWIGFunction", class('driesner07_H2O_NaCl_VL_xv_pT'))

# Start of driesner07_H2O_NaCl_VL_p_Txv

`driesner07_H2O_NaCl_VL_p_Txv` = function(T_K, x, p0, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_VL_p_Txv', T_K, x, p0, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_VL_p_Txv`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_VL_p_Txv`, "inputTypes") = c('numeric', 'numeric', 'numeric')
class(`driesner07_H2O_NaCl_VL_p_Txv`) = c("SWIGFunction", class('driesner07_H2O_NaCl_VL_p_Txv'))

# Start of driesner07_H2O_NaCl_VL_p_Txl

`driesner07_H2O_NaCl_VL_p_Txl` = function(T_K, x, p0, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_VL_p_Txl', T_K, x, p0, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_VL_p_Txl`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_VL_p_Txl`, "inputTypes") = c('numeric', 'numeric', 'numeric')
class(`driesner07_H2O_NaCl_VL_p_Txl`) = c("SWIGFunction", class('driesner07_H2O_NaCl_VL_p_Txl'))

# Start of driesner07_H2O_NaCl_VL_rhov_pT

`driesner07_H2O_NaCl_VL_rhov_pT` = function(p_Pa, T_K, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_VL_rhov_pT', p_Pa, T_K, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_VL_rhov_pT`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_VL_rhov_pT`, "inputTypes") = c('numeric', 'numeric')
class(`driesner07_H2O_NaCl_VL_rhov_pT`) = c("SWIGFunction", class('driesner07_H2O_NaCl_VL_rhov_pT'))

# Start of driesner07_H2O_NaCl_VL_rhol_pT

`driesner07_H2O_NaCl_VL_rhol_pT` = function(p_Pa, T_K, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_VL_rhol_pT', p_Pa, T_K, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_VL_rhol_pT`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_VL_rhol_pT`, "inputTypes") = c('numeric', 'numeric')
class(`driesner07_H2O_NaCl_VL_rhol_pT`) = c("SWIGFunction", class('driesner07_H2O_NaCl_VL_rhol_pT'))

# Start of driesner07_H2O_NaCl_LH_xl_pT

`driesner07_H2O_NaCl_LH_xl_pT` = function(p, T, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_LH_xl_pT', p, T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_LH_xl_pT`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_LH_xl_pT`, "inputTypes") = c('numeric', 'numeric')
class(`driesner07_H2O_NaCl_LH_xl_pT`) = c("SWIGFunction", class('driesner07_H2O_NaCl_LH_xl_pT'))

# Start of driesner07_H2O_NaCl_VH_xv_pT

`driesner07_H2O_NaCl_VH_xv_pT` = function(p, T, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_VH_xv_pT', p, T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_VH_xv_pT`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_VH_xv_pT`, "inputTypes") = c('numeric', 'numeric')
class(`driesner07_H2O_NaCl_VH_xv_pT`) = c("SWIGFunction", class('driesner07_H2O_NaCl_VH_xv_pT'))

# Start of driesner07_H2O_NaCl_VLH_p_T

`driesner07_H2O_NaCl_VLH_p_T` = function(T, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_VLH_p_T', T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_VLH_p_T`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_VLH_p_T`, "inputTypes") = c('numeric')
class(`driesner07_H2O_NaCl_VLH_p_T`) = c("SWIGFunction", class('driesner07_H2O_NaCl_VLH_p_T'))

# Start of driesner07_H2O_NaCl_VLH_xl_T

`driesner07_H2O_NaCl_VLH_xl_T` = function(T, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_VLH_xl_T', T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_VLH_xl_T`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_VLH_xl_T`, "inputTypes") = c('numeric')
class(`driesner07_H2O_NaCl_VLH_xl_T`) = c("SWIGFunction", class('driesner07_H2O_NaCl_VLH_xl_T'))

# Start of driesner07_H2O_NaCl_VLH_xv_T

`driesner07_H2O_NaCl_VLH_xv_T` = function(T, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_VLH_xv_T', T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_VLH_xv_T`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_VLH_xv_T`, "inputTypes") = c('numeric')
class(`driesner07_H2O_NaCl_VLH_xv_T`) = c("SWIGFunction", class('driesner07_H2O_NaCl_VLH_xv_T'))

# Start of driesner07_H2O_NaCl_NaCl_solubility_xv_pT

`driesner07_H2O_NaCl_NaCl_solubility_xv_pT` = function(p, T, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_NaCl_solubility_xv_pT', p, T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_NaCl_solubility_xv_pT`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_NaCl_solubility_xv_pT`, "inputTypes") = c('numeric', 'numeric')
class(`driesner07_H2O_NaCl_NaCl_solubility_xv_pT`) = c("SWIGFunction", class('driesner07_H2O_NaCl_NaCl_solubility_xv_pT'))

# Start of driesner07_H2O_NaCl_NaCl_solubility_xl_pT

`driesner07_H2O_NaCl_NaCl_solubility_xl_pT` = function(p, T, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_NaCl_solubility_xl_pT', p, T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_NaCl_solubility_xl_pT`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_NaCl_solubility_xl_pT`, "inputTypes") = c('numeric', 'numeric')
class(`driesner07_H2O_NaCl_NaCl_solubility_xl_pT`) = c("SWIGFunction", class('driesner07_H2O_NaCl_NaCl_solubility_xl_pT'))

# Start of driesner07_H2O_NaCl_NaCl_solubility_x_pT

`driesner07_H2O_NaCl_NaCl_solubility_x_pT` = function(p, T, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_NaCl_solubility_x_pT', p, T, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_NaCl_solubility_x_pT`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_NaCl_solubility_x_pT`, "inputTypes") = c('numeric', 'numeric')
class(`driesner07_H2O_NaCl_NaCl_solubility_x_pT`) = c("SWIGFunction", class('driesner07_H2O_NaCl_NaCl_solubility_x_pT'))

# Start of driesner07_H2O_NaCl_rho_singlephase_pTx

`driesner07_H2O_NaCl_rho_singlephase_pTx` = function(p_Pa, T_K, x, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_rho_singlephase_pTx', p_Pa, T_K, x, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_rho_singlephase_pTx`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_rho_singlephase_pTx`, "inputTypes") = c('numeric', 'numeric', 'numeric')
class(`driesner07_H2O_NaCl_rho_singlephase_pTx`) = c("SWIGFunction", class('driesner07_H2O_NaCl_rho_singlephase_pTx'))

# Start of driesner07_H2O_NaCl_vm_singlephase_pTx

`driesner07_H2O_NaCl_vm_singlephase_pTx` = function(p_Pa, T_K, x, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_vm_singlephase_pTx', p_Pa, T_K, x, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_vm_singlephase_pTx`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_vm_singlephase_pTx`, "inputTypes") = c('numeric', 'numeric', 'numeric')
class(`driesner07_H2O_NaCl_vm_singlephase_pTx`) = c("SWIGFunction", class('driesner07_H2O_NaCl_vm_singlephase_pTx'))

# Start of driesner07_H2O_NaCl_h_singlephase_pTx

`driesner07_H2O_NaCl_h_singlephase_pTx` = function(p_Pa, T_K, x, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_h_singlephase_pTx', p_Pa, T_K, x, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_h_singlephase_pTx`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_h_singlephase_pTx`, "inputTypes") = c('numeric', 'numeric', 'numeric')
class(`driesner07_H2O_NaCl_h_singlephase_pTx`) = c("SWIGFunction", class('driesner07_H2O_NaCl_h_singlephase_pTx'))

# Start of driesner07_H2O_NaCl_cp_singlephase_pTx

`driesner07_H2O_NaCl_cp_singlephase_pTx` = function(p_Pa, T_K, x, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_cp_singlephase_pTx', p_Pa, T_K, x, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_cp_singlephase_pTx`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_cp_singlephase_pTx`, "inputTypes") = c('numeric', 'numeric', 'numeric')
class(`driesner07_H2O_NaCl_cp_singlephase_pTx`) = c("SWIGFunction", class('driesner07_H2O_NaCl_cp_singlephase_pTx'))

# Start of driesner07_H2O_NaCl_mass_fraction_liquid

`driesner07_H2O_NaCl_mass_fraction_liquid` = function(p_Pa, T_K, x, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_mass_fraction_liquid', p_Pa, T_K, x, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_mass_fraction_liquid`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_mass_fraction_liquid`, "inputTypes") = c('numeric', 'numeric', 'numeric')
class(`driesner07_H2O_NaCl_mass_fraction_liquid`) = c("SWIGFunction", class('driesner07_H2O_NaCl_mass_fraction_liquid'))

# Start of driesner07_H2O_NaCl_mass_fraction_vapor

`driesner07_H2O_NaCl_mass_fraction_vapor` = function(p_Pa, T_K, x, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_mass_fraction_vapor', p_Pa, T_K, x, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_mass_fraction_vapor`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_mass_fraction_vapor`, "inputTypes") = c('numeric', 'numeric', 'numeric')
class(`driesner07_H2O_NaCl_mass_fraction_vapor`) = c("SWIGFunction", class('driesner07_H2O_NaCl_mass_fraction_vapor'))

# Start of driesner07_H2O_NaCl_volume_fraction_liquid

`driesner07_H2O_NaCl_volume_fraction_liquid` = function(p_Pa, T_K, x, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_volume_fraction_liquid', p_Pa, T_K, x, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_volume_fraction_liquid`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_volume_fraction_liquid`, "inputTypes") = c('numeric', 'numeric', 'numeric')
class(`driesner07_H2O_NaCl_volume_fraction_liquid`) = c("SWIGFunction", class('driesner07_H2O_NaCl_volume_fraction_liquid'))

# Start of driesner07_H2O_NaCl_volume_fraction_vapor

`driesner07_H2O_NaCl_volume_fraction_vapor` = function(p_Pa, T_K, x, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_volume_fraction_vapor', p_Pa, T_K, x, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_volume_fraction_vapor`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_volume_fraction_vapor`, "inputTypes") = c('numeric', 'numeric', 'numeric')
class(`driesner07_H2O_NaCl_volume_fraction_vapor`) = c("SWIGFunction", class('driesner07_H2O_NaCl_volume_fraction_vapor'))

# Start of driesner07_H2O_NaCl_volume_fraction_halite

`driesner07_H2O_NaCl_volume_fraction_halite` = function(p_Pa, T_K, x, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_volume_fraction_halite', p_Pa, T_K, x, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_volume_fraction_halite`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_volume_fraction_halite`, "inputTypes") = c('numeric', 'numeric', 'numeric')
class(`driesner07_H2O_NaCl_volume_fraction_halite`) = c("SWIGFunction", class('driesner07_H2O_NaCl_volume_fraction_halite'))

# Start of driesner07_H2O_NaCl_T_rhopx

`driesner07_H2O_NaCl_T_rhopx` = function(rho, p_Pa, x, TK0, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_T_rhopx', rho, p_Pa, x, TK0, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_T_rhopx`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_T_rhopx`, "inputTypes") = c('numeric', 'numeric', 'numeric', 'numeric')
class(`driesner07_H2O_NaCl_T_rhopx`) = c("SWIGFunction", class('driesner07_H2O_NaCl_T_rhopx'))

# Start of driesner07_H2O_NaCl_T_phx

`driesner07_H2O_NaCl_T_phx` = function(p_Pa, h, x, TK0, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_T_phx', p_Pa, h, x, TK0, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_T_phx`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_T_phx`, "inputTypes") = c('numeric', 'numeric', 'numeric', 'numeric')
class(`driesner07_H2O_NaCl_T_phx`) = c("SWIGFunction", class('driesner07_H2O_NaCl_T_phx'))

# Start of driesner07_H2O_NaCl_volume_fraction_liquid_rhopx

`driesner07_H2O_NaCl_volume_fraction_liquid_rhopx` = function(rho, p_Pa, x, TK0, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_volume_fraction_liquid_rhopx', rho, p_Pa, x, TK0, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_volume_fraction_liquid_rhopx`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_volume_fraction_liquid_rhopx`, "inputTypes") = c('numeric', 'numeric', 'numeric', 'numeric')
class(`driesner07_H2O_NaCl_volume_fraction_liquid_rhopx`) = c("SWIGFunction", class('driesner07_H2O_NaCl_volume_fraction_liquid_rhopx'))

# Start of driesner07_H2O_NaCl_rho_pTx

`driesner07_H2O_NaCl_rho_pTx` = function(p_Pa, T_K, x, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_rho_pTx', p_Pa, T_K, x, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_rho_pTx`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_rho_pTx`, "inputTypes") = c('numeric', 'numeric', 'numeric')
class(`driesner07_H2O_NaCl_rho_pTx`) = c("SWIGFunction", class('driesner07_H2O_NaCl_rho_pTx'))

# Start of driesner07_H2O_NaCl_h_pTx

`driesner07_H2O_NaCl_h_pTx` = function(p_Pa, T_K, x, .copy = FALSE)
{
  ;.Call('R_swig_driesner07_H2O_NaCl_h_pTx', p_Pa, T_K, x, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`driesner07_H2O_NaCl_h_pTx`, 'returnType') = 'numeric'
attr(`driesner07_H2O_NaCl_h_pTx`, "inputTypes") = c('numeric', 'numeric', 'numeric')
class(`driesner07_H2O_NaCl_h_pTx`) = c("SWIGFunction", class('driesner07_H2O_NaCl_h_pTx'))

# Start of klyukinetal2017_viscosity

`klyukinetal2017_viscosity` = function(rho, T, xNaCl, .copy = FALSE)
{
  ;.Call('R_swig_klyukinetal2017_viscosity', rho, T, xNaCl, as.logical(.copy), PACKAGE='geofluidprop');
  
}

attr(`klyukinetal2017_viscosity`, 'returnType') = 'numeric'
attr(`klyukinetal2017_viscosity`, "inputTypes") = c('numeric', 'numeric', 'numeric')
class(`klyukinetal2017_viscosity`) = c("SWIGFunction", class('klyukinetal2017_viscosity'))




#' H2O-NaCl viscosity function in Klyukin et al. (2017)
#' #'
#' @param rho density [kg/m^3]
#' @param T temperature [K]
#' @param xNaCl NaCl mole fraction [mol/mol]
#'
#' @return viscosity [Pa s]
#' @export